language: node_js
node_js:
  - "8.9.3"
branches:
  only:
    - master
    - /^feat-.*$/
script:
  - echo "Deploing!"
  - npm install
  - ng build
install:
  - npm install -g firebase-tools
  - npm install -g angular-cli
after_success:
  - echo "Deploing to firebase!"
  - if [ "$TRAVIS_BRANCH" == "master" ]; then firebase deploy --token $test; fi
